import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ClientLayout from "./clientLayout"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "AURAvEIN.IN",
  description: "Generated by AURAvEIN",
    generator: 'AURAvEIN',
  applicationName: "AURAvEIN",
  keywords: ["auravein", "fashion", "clothing", "premium", "online shopping"],
  authors: [{ name: "AURAvEIN" }],
  creator: "PRANAV",
  openGraph: {
    title: "AURAvEIN.IN",
    description: "Explore the latest trends in oversized fashion with AURAvEIN.",
    url: "https://auravein.in",
    siteName: "AURAvEIN",
    images: [
      {
        url: "/img.jpg",
        width: 1200,
        height: 630,
        alt: "AURAvEIN - Oversized Fashion",
      },
    ],
    locale: "en_US",
    type: "website",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
}
